In [1]:
import os
import pandas as pd
from sklearn.neighbors import NearestNeighbors
import numpy as np
from sklearn.utils import shuffle

In [21]:
class Recommend:
    def __init__(self, 
                 sample_sub_df,
                 transaction_df,
                 features_df):
        self.sample_sub_df = sample_sub_df
        self.transaction_df = transaction_df
        self.features_df = features_df
        self.model = NearestNeighbors(n_neighbors=12)
        
    
    
    def predict():
        pass
    
    def find_centroid(self, article_list):
        all_features = []

        for article in article_list:

            block = self.feature_df[self.feature_df["article_id"] == article].iloc[:, 1:-1]
            if block.shape[0] > 0:
                all_features.append(block.to_numpy())
                
        all_features = np.concatenate(np.array(all_features))
            
    
    def write_results():
        pass
    def generate_recommendations(self):
        # make predictions for customers in sample_sub_df
        
        customer_history = self.sample_sub_df.merge(self.transaction_df)
        customer_history.drop(['t_dat', 'price', 'sales_channel_id'], axis=1, inplace=True)
        customer_group = customer_history.groupby("customer_id")
        
        for name, group in customer_group:
            if len(group) > 0:
                print(name)
#                 self.find_centroid(group["article_id"].tolist())
                print(group["article_id"].tolist())
                break
                # send 'group' to find_centroid, returns an embedding
                # send embedding to predict, returns predictions
                # send predictions to write_results
            
            
class evaluate:
    def __init__(results_path=""):
        self.results_df = pd.read_csv(results_path)
        
    def calc_mean_avg_precision():
        pass
            

In [22]:
sample_sub_path = "C:/Users/ojubh\/Desktop/SEMESTER 2/Deep Learning/Final_Project/data/sample_submission.csv"
transaction_path = "C:/Users/ojubh\/Desktop/SEMESTER 2/Deep Learning/Final_Project/data/transactions_train.csv"
features_path = "C:/Users/ojubh\/Desktop/SEMESTER 2/Deep Learning/Final_Project/data/visual_embeddings_final.csv"

sample_sub_df = pd.read_csv(sample_sub_path)
transaction_df = pd.read_csv(transaction_path)
feature_df = pd.read_csv(features_path)

recommend = Recommend(sample_sub_df, transaction_df, feature_df)


In [23]:
recommend.generate_recommendations()

00000dbacae5abe5e23885899a1fa44253a17956c6d1c3d25f88aa139fdfc657
[625548001, 176209023, 627759010, 697138006, 568601006, 568601006, 607642008, 745232001, 656719005, 797065001, 797065001, 785186005, 694736004, 785710001, 812683013, 841260003, 887593002, 890498002, 795440001, 859416011, 568601043]


In [39]:
articles = [625548001, 176209023, 627759010, 697138006, 568601006, 568601006, 607642008, 745232001, 656719005, 797065001, 797065001, 785186005, 694736004, 785710001, 812683013, 841260003, 887593002, 890498002, 795440001, 859416011, 568601043]

all_features = []

for article in articles[:2]:

    block = feature_df[feature_df["article_id"] == article].iloc[:, 1:-1]
    print(block)

#     if block.shape[0] > 0:
#         all_features.append(block.to_numpy())
        
        


      feature_0  feature_1  feature_2  feature_3  feature_4  feature_5  \
6318   0.005906  -0.038544   0.112788  -0.001114  -0.047949   0.025035   

      feature_6  feature_7  feature_8  feature_9  ...  feature_246  \
6318   0.037177   0.068184  -0.008321   0.026323  ...     0.056265   

      feature_247  feature_248  feature_249  feature_250  feature_251  \
6318    -0.005186    -0.023714     0.015461    -0.056606    -0.026489   

      feature_252  feature_253  feature_254  feature_255  
6318    -0.094524    -0.011572    -0.099016    -0.022905  

[1 rows x 256 columns]
    feature_0  feature_1  feature_2  feature_3  feature_4  feature_5  \
29   0.016059   -0.06702    0.03415  -0.012584  -0.024609  -0.047817   

    feature_6  feature_7  feature_8  feature_9  ...  feature_246  feature_247  \
29   0.003319   0.108626   0.031268   0.006889  ...     0.073493     0.007281   

    feature_248  feature_249  feature_250  feature_251  feature_252  \
29     0.000825     0.018547    -0.048673 

In [36]:
trial = all_features

In [48]:
trial = trial[:2]

In [53]:
final = np.concatenate(np.array(trial))

In [57]:
final.shape

(2, 256)

In [55]:
np.sum(final, axis=0)

array([ 2.19644160e-02, -1.05564192e-01,  1.46938095e-01, -1.36978380e-02,
       -7.25577930e-02, -2.27824720e-02,  4.04966678e-02,  1.76809480e-01,
        2.29473290e-02,  3.32125890e-02, -1.27717484e-01, -3.39426190e-02,
        1.64950100e-02, -1.88613626e-01,  4.13838650e-02,  5.15136810e-02,
        1.48289224e-01, -2.88548338e-02,  6.00201010e-02,  8.44270440e-02,
       -1.52767574e-01, -5.59772000e-03,  1.47616044e-01, -4.14386040e-02,
       -2.50610465e-02,  3.42424330e-02, -8.60419870e-02, -8.42979160e-02,
        6.89175635e-02,  5.99847020e-02, -2.48760020e-02,  2.33822250e-02,
        1.39728908e-01, -1.13984457e-01,  2.86699670e-02, -2.79535460e-02,
        6.67729450e-02,  5.23951860e-02, -6.78336700e-02, -4.77489000e-04,
        1.48412565e-01,  5.25685795e-02,  1.72529840e-01,  8.69002217e-02,
       -1.82972020e-02, -9.43569390e-02,  2.41752310e-02, -6.60115330e-02,
       -7.22560440e-02,  6.15381720e-02, -1.39908923e-01,  1.01223739e-01,
       -9.60136300e-02, -

In [105]:
merged_customer_data = sample_sub.merge(trans_train, on="customer_id", how="inner")

In [106]:
merged_customer_data.drop(['t_dat', 'price', 'sales_channel_id'], inplace=True, axis=1)

In [107]:
customer_group = merged_customer_data.groupby("customer_id")

In [161]:
len(customer_group)

1362281

In [113]:
image_embeddings.drop("article_id", inplace=True, axis=1)
image_embeddings.drop("Unnamed: 0", axis=1, inplace=True)


In [118]:
x_train = image_embeddings.to_numpy()

In [119]:
neigh = 
neigh.fit(x_train)

NearestNeighbors(n_neighbors=12)

In [ ]:
## 4 articles, sum up over all featurss/ len()
## numpy_arr = [...]

In [121]:
neigh.kneighbors(numpy_arr.reshape(1, -1))

(array([[0.        , 0.1990896 , 0.22100405, 0.24072063, 0.2425537 ,
         0.24804528, 0.248834  , 0.25008156, 0.25129139, 0.26048417,
         0.26257267, 0.26783031]]),
 array([[    0,  3126, 20782, 18722,  3480,  7166,   285,  6675, 15009,
         10820, 18750, 10864]], dtype=int64))