In [1]:
import os
import pandas as pd
from sklearn.neighbors import NearestNeighbors
import numpy as np
from sklearn.utils import shuffle

In [59]:
class Recommend:
    def __init__(self, 
                 sample_sub_df,
                 transaction_df,
                 features_df):
        self.sample_sub_df = sample_sub_df
        self.transaction_df = transaction_df
        self.features_df = features_df
        self.model = NearestNeighbors(n_neighbors=12)
        
    
    
    def predict():
        pass
    
    def find_centroid(self, article_list):
        all_features = []

        for article in article_list:

            block = self.feature_df[self.feature_df["article_id"] == article].iloc[:, 1:-1]
            if block.shape[0] > 0:
                all_features.append(block.to_numpy())
                
        all_features = np.concatenate(np.array(all_features))
        print(all_features.shape)
        
        return np.sum(all_features, axis=0)/all_features.shape[0]
            
    
    def write_results():
        pass
    def generate_recommendations(self):
        # make predictions for customers in sample_sub_df
        
        customer_history = self.sample_sub_df.merge(self.transaction_df)
        customer_history.drop(['t_dat', 'price', 'sales_channel_id'], axis=1, inplace=True)
        customer_group = customer_history.groupby("customer_id")
        
        for name, group in customer_group:
            if len(group) > 0:
                average_embds = self.find_centroid(group["article_id"].tolist())
                break
                # send 'group' to find_centroid, returns an embedding --> done
                # send embedding to predict, returns predictions
                # send predictions to write_results
            
            
class evaluate:
    def __init__(results_path=""):
        self.results_df = pd.read_csv(results_path)
        
    def calc_mean_avg_precision():
        pass
            

In [60]:
sample_sub_path = "C:/Users/ojubh\/Desktop/SEMESTER 2/Deep Learning/Final_Project/data/sample_submission.csv"
transaction_path = "C:/Users/ojubh\/Desktop/SEMESTER 2/Deep Learning/Final_Project/data/transactions_train.csv"
features_path = "C:/Users/ojubh\/Desktop/SEMESTER 2/Deep Learning/Final_Project/data/visual_embeddings_final.csv"

sample_sub_df = pd.read_csv(sample_sub_path)
transaction_df = pd.read_csv(transaction_path)
feature_df = pd.read_csv(features_path)

recommend = Recommend(sample_sub_df, transaction_df, feature_df)


In [61]:
recommend.generate_recommendations()

00000dbacae5abe5e23885899a1fa44253a17956c6d1c3d25f88aa139fdfc657
[625548001, 176209023, 627759010, 697138006, 568601006, 568601006, 607642008, 745232001, 656719005, 797065001, 797065001, 785186005, 694736004, 785710001, 812683013, 841260003, 887593002, 890498002, 795440001, 859416011, 568601043]


In [39]:
articles = [625548001, 176209023, 627759010, 697138006, 568601006, 568601006, 607642008, 745232001, 656719005, 797065001, 797065001, 785186005, 694736004, 785710001, 812683013, 841260003, 887593002, 890498002, 795440001, 859416011, 568601043]

all_features = []

for article in articles[:2]:

    block = feature_df[feature_df["article_id"] == article].iloc[:, 1:-1]
    print(block)

#     if block.shape[0] > 0:
#         all_features.append(block.to_numpy())
        
        


      feature_0  feature_1  feature_2  feature_3  feature_4  feature_5  \
6318   0.005906  -0.038544   0.112788  -0.001114  -0.047949   0.025035   

      feature_6  feature_7  feature_8  feature_9  ...  feature_246  \
6318   0.037177   0.068184  -0.008321   0.026323  ...     0.056265   

      feature_247  feature_248  feature_249  feature_250  feature_251  \
6318    -0.005186    -0.023714     0.015461    -0.056606    -0.026489   

      feature_252  feature_253  feature_254  feature_255  
6318    -0.094524    -0.011572    -0.099016    -0.022905  

[1 rows x 256 columns]
    feature_0  feature_1  feature_2  feature_3  feature_4  feature_5  \
29   0.016059   -0.06702    0.03415  -0.012584  -0.024609  -0.047817   

    feature_6  feature_7  feature_8  feature_9  ...  feature_246  feature_247  \
29   0.003319   0.108626   0.031268   0.006889  ...     0.073493     0.007281   

    feature_248  feature_249  feature_250  feature_251  feature_252  \
29     0.000825     0.018547    -0.048673 

In [36]:
trial = all_features

In [48]:
trial = trial[:2]

In [53]:
final = np.concatenate(np.array(trial))

In [57]:
final.shape

(2, 256)

In [58]:
np.sum(final, axis=0)/2

array([ 1.09822080e-02, -5.27820960e-02,  7.34690475e-02, -6.84891900e-03,
       -3.62788965e-02, -1.13912360e-02,  2.02483339e-02,  8.84047400e-02,
        1.14736645e-02,  1.66062945e-02, -6.38587420e-02, -1.69713095e-02,
        8.24750500e-03, -9.43068130e-02,  2.06919325e-02,  2.57568405e-02,
        7.41446120e-02, -1.44274169e-02,  3.00100505e-02,  4.22135220e-02,
       -7.63837870e-02, -2.79886000e-03,  7.38080220e-02, -2.07193020e-02,
       -1.25305232e-02,  1.71212165e-02, -4.30209935e-02, -4.21489580e-02,
        3.44587818e-02,  2.99923510e-02, -1.24380010e-02,  1.16911125e-02,
        6.98644540e-02, -5.69922285e-02,  1.43349835e-02, -1.39767730e-02,
        3.33864725e-02,  2.61975930e-02, -3.39168350e-02, -2.38744500e-04,
        7.42062825e-02,  2.62842898e-02,  8.62649200e-02,  4.34501109e-02,
       -9.14860100e-03, -4.71784695e-02,  1.20876155e-02, -3.30057665e-02,
       -3.61280220e-02,  3.07690860e-02, -6.99544615e-02,  5.06118695e-02,
       -4.80068150e-02, -

In [105]:
merged_customer_data = sample_sub.merge(trans_train, on="customer_id", how="inner")

In [106]:
merged_customer_data.drop(['t_dat', 'price', 'sales_channel_id'], inplace=True, axis=1)

In [107]:
customer_group = merged_customer_data.groupby("customer_id")

In [161]:
len(customer_group)

1362281

In [113]:
image_embeddings.drop("article_id", inplace=True, axis=1)
image_embeddings.drop("Unnamed: 0", axis=1, inplace=True)


In [118]:
x_train = image_embeddings.to_numpy()

In [119]:
neigh = 
neigh.fit(x_train)

NearestNeighbors(n_neighbors=12)

In [ ]:
## 4 articles, sum up over all featurss/ len()
## numpy_arr = [...]

In [121]:
neigh.kneighbors(numpy_arr.reshape(1, -1))

(array([[0.        , 0.1990896 , 0.22100405, 0.24072063, 0.2425537 ,
         0.24804528, 0.248834  , 0.25008156, 0.25129139, 0.26048417,
         0.26257267, 0.26783031]]),
 array([[    0,  3126, 20782, 18722,  3480,  7166,   285,  6675, 15009,
         10820, 18750, 10864]], dtype=int64))